AWSTemplateFormatVersion: '2010-09-09'
Description: Base stack to create container day resources

Resources:
  ECSTaskRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: ['sts:AssumeRole']
        Path: /