AWSTemplateFormatVersion: '2010-09-09'
Description: Base stack to create container day resources

Resources:
  ECSTaskRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::*:root"
            Action: ['sts:AssumeRole']
            Condition:
              StringLike:
                aws:PrincipalOrgID: "o-4ti206djdv"
        Policies:
          - PolicyName: root
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Resource: "*"
                  Effect: Allow
                  Action:
                    - s3:GetObject
        Path: /